export const icons: Record<string, string> = {
  html: 'fab fa-html5',
  css: 'fab fa-css3-alt',
  javascript: 'fab fa-js',
  react: 'fab fa-react',
  vue: 'fab fa-vuejs',
  angular: 'fab fa-angular',
  git: 'fab fa-git-alt',
  node: 'fab fa-node-js',
  npm: 'fab fa-npm',
  docker: 'fab fa-docker',
  database: 'fas fa-database',
  cloud: 'fas fa-cloud',
  location: 'fas fa-map-marker-alt',
  nationality: 'fas fa-passport',
  phone: 'fas fa-phone',
  email: 'fas fa-envelope',
  birthday: 'fas fa-birthday-cake',
  maritalStatus: 'fas fa-user-alt',
  linkedin: 'fab fa-linkedin',
  github: 'fab fa-github',
  phd: 'fas fa-book',
  master: 'fas fa-scroll',
  bachelor: 'fas fa-graduation-cap',
  company: 'fas fa-building',
  developer: 'fas fa-laptop-code',
  notFound: 'fas fa-question-circle',
};

export const EducationType = {
  Degree: 'degree',
  Certification: 'certification',
};

export const SkillsType = {
  Languages: 'language',
  Technologies: 'technology',
};

export const most_spoken_languages = [
  { name: 'Mandarin Chinese', iso: 'zh', flag: 'CN' },
  { name: 'Spanish', iso: 'es', flag: 'ES' },
  { name: 'English', iso: 'en', flag: 'US' },
  { name: 'Hindi', iso: 'hi', flag: 'IN' },
  { name: 'Arabic', iso: 'ar', flag: 'SA' },
  { name: 'Bengali', iso: 'bn', flag: 'BD' },
  { name: 'Portuguese', iso: 'pt', flag: 'BR' },
  { name: 'Russian', iso: 'ru', flag: 'RU' },
  { name: 'Japanese', iso: 'ja', flag: 'JP' },
  { name: 'Lahnda {Western Punjabi}', iso: 'pa', flag: 'PK' },
  { name: 'Marathi', iso: 'mr', flag: 'IN' },
  { name: 'Telugu', iso: 'te', flag: 'IN' },
  { name: 'Turkish', iso: 'tr', flag: 'TR' },
  { name: 'Korean', iso: 'ko', flag: 'KR' },
  { name: 'French', iso: 'fr', flag: 'FR' },
  { name: 'German', iso: 'de', flag: 'DE' },
  { name: 'Vietnamese', iso: 'vi', flag: 'VN' },
  { name: 'Tamil', iso: 'ta', flag: 'IN' },
  { name: 'Urdu', iso: 'ur', flag: 'PK' },
  { name: 'Javanese', iso: 'jv', flag: 'ID' },
  { name: 'Italian', iso: 'it', flag: 'IT' },
  { name: 'Egyptian Arabic', iso: 'arz', flag: 'EG' },
  { name: 'Gujarati', iso: 'gu', flag: 'IN' },
  { name: 'Iranian Persian', iso: 'fa', flag: 'IR' },
  { name: 'Bhojpuri', iso: 'bho', flag: 'IN' },
  { name: 'Southern Min {Hokkien-Taiwanese}', iso: 'nan', flag: 'TW' },
  { name: 'Hausa', iso: 'ha', flag: 'NG' },
  { name: 'Kannada', iso: 'kn', flag: 'IN' },
  { name: 'Indonesian', iso: 'id', flag: 'ID' },
  { name: 'Polish', iso: 'pl', flag: 'PL' },
  { name: 'Yoruba', iso: 'yo', flag: 'NG' },
  { name: 'Xiang Chinese', iso: 'hsn', flag: 'CN' },
  { name: 'Malayalam', iso: 'ml', flag: 'IN' },
  { name: 'Odia {Oriya}', iso: 'or', flag: 'IN' },
  { name: 'Maithili', iso: 'mai', flag: 'IN' },
  { name: 'Burmese', iso: 'my', flag: 'MM' },
  { name: 'Sunda', iso: 'su', flag: 'ID' },
  { name: 'Sudanese Arabic', iso: 'apd', flag: 'SD' },
  { name: 'Algerian Arabic', iso: 'arq', flag: 'DZ' },
  { name: 'Moroccan Arabic', iso: 'ary', flag: 'MA' },
  { name: 'Ukrainian', iso: 'uk', flag: 'UA' },
  { name: 'Igbo', iso: 'ig', flag: 'NG' },
  { name: 'Northern Uzbek', iso: 'uz', flag: 'UZ' },
  { name: 'Sindhi', iso: 'sd', flag: 'PK' },
  { name: 'North Levantine Arabic', iso: 'apc', flag: 'SY' },
  { name: 'Romanian', iso: 'ro', flag: 'RO' },
  { name: 'Tagalog', iso: 'tl', flag: 'PH' },
  { name: 'Dutch', iso: 'nl', flag: 'NL' },
  { name: 'Saʽidi Arabic', iso: 'aec', flag: 'EG' },
  { name: 'Gan Chinese', iso: 'gan', flag: 'CN' },
  { name: 'Amharic', iso: 'am', flag: 'ET' },
  { name: 'Northern Pashto', iso: 'pbu', flag: 'AF' },
  { name: 'Magahi', iso: 'mag', flag: 'IN' },
  { name: 'Thai', iso: 'th', flag: 'TH' },
  { name: 'Saraiki', iso: 'skr', flag: 'PK' },
  { name: 'Khmer', iso: 'km', flag: 'KH' },
  { name: 'Chhattisgarhi', iso: 'hne', flag: 'IN' },
  { name: 'Somali', iso: 'so', flag: 'SO' },
  { name: 'Cebuano', iso: 'ceb', flag: 'PH' },
  { name: 'Nepali', iso: 'ne', flag: 'NP' },
  { name: 'Mesopotamian Arabic', iso: 'acm', flag: 'IQ' },
  { name: 'Assamese', iso: 'as', flag: 'IN' },
  { name: 'Sinhalese', iso: 'si', flag: 'LK' },
  { name: 'Northern Kurdish', iso: 'kmr', flag: 'IQ' },
  { name: 'Hejazi Arabic', iso: 'acw', flag: 'SA' },
  { name: 'Nigerian Pidgin', iso: 'pcm', flag: 'NG' },
  { name: 'Greek', iso: 'el', flag: 'GR' },
  { name: 'Chittagonian', iso: 'ctg', flag: 'BD' },
  { name: 'Kazakh', iso: 'kk', flag: 'KZ' },
  { name: 'Deccan', iso: 'dcc', flag: 'IN' },
  { name: 'Hungarian', iso: 'hu', flag: 'HU' },
  { name: 'Kinyarwanda', iso: 'rw', flag: 'RW' },
  { name: 'Zulu', iso: 'zu', flag: 'ZA' },
  { name: 'South Azerbaijani', iso: 'azb', flag: 'IR' },
  { name: 'Tunisian Arabic', iso: 'aeb', flag: 'TN' },
  { name: 'Sanaani Spoken Arabic', iso: 'ayn', flag: 'YE' },
  { name: 'Min Bei Chinese', iso: 'cdo', flag: 'CN' },
  { name: 'Southern Pashto', iso: 'pbt', flag: 'PK' },
  { name: 'Rundi', iso: 'rn', flag: 'BI' },
  { name: 'Czech', iso: 'cs', flag: 'CZ' },
  { name: 'Uyghur', iso: 'ug', flag: 'CN' },
  { name: 'Sylheti', iso: 'syl', flag: 'BD' },
  { name: 'Swedish', iso: 'sv', flag: 'SE' },
  { name: 'Hiligaynon', iso: 'hil', flag: 'PH' },
  { name: 'Haitian Creole', iso: 'ht', flag: 'HT' },
  { name: 'Eastern Min {Fuzhou dialect}', iso: 'cdo', flag: 'CN' },
  { name: 'Ilocano', iso: 'ilo', flag: 'PH' },
  { name: 'Belarusian', iso: 'be', flag: 'BY' },
  { name: 'Azerbaijani', iso: 'az', flag: 'AZ' },
  { name: 'Hebrew', iso: 'he', flag: 'IL' },
  { name: 'Bulgarian', iso: 'bg', flag: 'BG' },
  { name: 'Shona', iso: 'sn', flag: 'ZW' },
  { name: 'Tigrinya', iso: 'ti', flag: 'ER' },
  { name: 'Danish', iso: 'da', flag: 'DK' },
  { name: 'Finnish', iso: 'fi', flag: 'FI' },
  { name: 'Norwegian', iso: 'no', flag: 'NO' },
  { name: 'Slovak', iso: 'sk', flag: 'SK' },
  { name: 'Serbian', iso: 'sr', flag: 'RS' },
  { name: 'Lithuanian', iso: 'lt', flag: 'LT' },
  { name: 'Latvian', iso: 'lv', flag: 'LV' },
  { name: 'Slovenian', iso: 'sl', flag: 'SI' },
  { name: 'Croatian', iso: 'hr', flag: 'HR' },
  { name: 'Estonian', iso: 'et', flag: 'EE' },
  { name: 'Maltese', iso: 'mt', flag: 'MT' },
  { name: 'Irish', iso: 'ga', flag: 'IE' },
];

export const languageLevelToPercent: Record<string, number> = {
  A1: 10,
  A2: 25,
  B1: 45,
  B2: 65,
  C1: 85,
  C2: 100,
};
